spring:
  application:
    name: bankcards
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:7878}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankcards}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.yaml
  profiles:
    active: dev
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        page-parameter: page
        size-parameter: size
        prefix: ''

server:
  port: 8080

app:
  security:
    signing-key: ${JWT_KEY:53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855}
    card-encryption-key: ${CE_KEY:K12kb12ck1fDk15D}

logging:
  level:
    org:
      springframework:
        security: DEBUG